version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - develop
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/Itinerary.Api
after_build:
  # For once the build has completed
artifacts:
  # Just skip
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet test ./test/Itinerary.Tests/Itinerary.Tests.csproj
on_finish :
  # any cleanup in here
deploy: off
