version: 2

working_directory: &working_directory /home/circleci/project
key: &src-cache-key src-{{ .Branch }}-{{ .Revision }}
key: &art-app-key art-app-{{ .Branch }}-{{ .Revision }}

restore_cache: &restore_src
  key: *src-cache-key

docker: &docker_node
  - image: circleci/node:9.2.1

run: &npm_install
  name: Install npm dependencies
  command: |
    echo Project path: ${project_path}
    cd ${project_path}
    npm config set progress=false
    npm install -g firebase-tools
    npm install

run: &npm_build
  name: Run prod build
  command: |
    echo Project path: ${project_path}
    cd ${project_path}
    node node_modules/@angular/cli/bin/ng build

jobs:
  checkout_source:
    docker: *docker_node
    working_directory: ~/project
    steps:
      - checkout
      - save_cache:
          key: *src-cache-key
          paths:
            - ~/project
  build_app:
    environment:
      project_path: .
    docker: *docker_node
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_src
      - restore_cache:
          key: deps-app-npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run: *npm_install
      - save_cache:
          key: deps-app-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: *npm_build
      - save_cache:
          key: *art-app-key
          paths:
            - dist
  emit_artifacts:
    docker: *docker_node
    working_directory: *working_directory
    steps:
      - restore_cache:
          key: *art-app-key
      - run:
          name: Publish artifacts
          command: |
            firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - checkout_source
      - build_app:
          requires:
            - checkout_source
      - emit_artifacts:
          filters:
            branches:
              only:
                - develop
          requires:
            - build_app
